org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.unsafe.watch-fs=false
android.useAndroidX=true
kotlin.code.style=official
# v1.0.0：沙箱限制 Kotlin daemon 写 tmp（AccessDeniedException），固化规划书对策：
# 编译走 Gradle 进程内执行，牺牲少量速度换取稳定
kotlin.compiler.execution.strategy=in-process
android.nonTransitiveRClass=true
# ?? AGP ??? aapt2(8.5.2) ????????????? SDK ???????
android.aapt2FromMavenOverride=C:/Android/sdk/build-tools/34.0.0/aapt2.exe
